-- -- disable netrw at the very start of your init.lua
-- vim.g.loaded_netrw = 1
-- vim.g.loaded_netrwPlugin = 1
--
-- -- set termguicolors to enable highlight groups
-- vim.opt.termguicolors = true
--
-- -- empty setup using defaults
-- require("nvim-tree").setup()
--
-- -- OR setup with some options
-- require("nvim-tree").setup({
--   sort = {
--     sorter = "case_sensitive",
--   },
--   view = {
--     width = 30,
--   },
--   renderer = {
--     group_empty = true,
--   },
--   filters = {
--     dotfiles = true,
--   },
-- })
--
-- local map = vim.api.nvim_set_keymap
-- local opts = { noremap = true, silent = true }

-- Toggle NvimTree with Leader + pv
-- map('n', '<C-n>', ':NvimTreeToggle<CR>', opts)
-- map('n', '<Leader>pv', ':NvimTreeFocus<CR>', opts)

