local dap = require("dap")
local dapui = require("dapui")

return function()
	-- Optional: Configure custom DAP key mappings
	vim.keymap.set("n", "<F4>", dapui.toggle, { desc = "Debug: Toggle UI" })
	vim.keymap.set("n", "<F5>", function()
		dap.continue()
	end)
	vim.keymap.set("n", "<F6>", dap.run_to_cursor, { desc = "Debug: Run to cursor" })
	vim.keymap.set("n", "<leader>d", function()
		dap.continue()
	end)
	vim.keymap.set("n", "<leader>n", function()
		dap.step_over()
	end)
	vim.keymap.set("n", "<F11>", function()
		dap.step_into()
	end)
	vim.keymap.set("n", "<leader>i", function()
		dap.step_into()
	end)
	vim.keymap.set("n", "<F12>", function()
		dap.step_out()
	end)
	vim.keymap.set("n", "<Leader>b", function()
		dap.toggle_breakpoint()
	end)
	vim.keymap.set("n", "<Leader>B", function()
		dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
	end)
end
